# Generated by Django 5.2.7 on 2025-10-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jcJourney', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About me'},
        ),
        migrations.AlterModelOptions(
            name='learningjourney',
            options={'verbose_name_plural': 'Learning Journey'},
        ),
    ]
