# Generated by Django 5.2.7 on 2025-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jcJourney', '0002_alter_aboutme_options_alter_learningjourney_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningjourney',
            name='date',
            field=models.DateField(),
        ),
    ]
